if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

alias ls='ls --color=auto --sort=extension'
eval $(dircolors ~/.dircolors)
PS1='\[\033[01;31m\]\u\[\033[00m\]@\[\033[01;33m\]\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

