name: Verify Helm Chart Values

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r test/requirements.txt

      - name: Verify helm chart values
        run: |
          python3 test/verify_helm_charts.py
    