name: Verify Helm Chart Values

on:
  push:
    branches: [ feat/ci/verify_chart_values ]
  pull_request:
    branches: [ feat/ci/verify_chart_values ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt

      - name: Verify helm chart values
        run: |
          python3 test/verify_helm_chart_values.py
    